name: Build Docker Image

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Biuld Docker image and push it to registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build Docker image
      run: docker build . --tag ghcr.io/a-sinkavets/bitcoin:0.21.0
    -
      name: Vulnerability Scan
      id: scan
      uses: sysdiglabs/scan-action@v1
      with:
        image-tag: ghcr.io/a-sinkavets/bitcoin:0.21.0
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        sysdig-secure-url: https://eu1.app.sysdig.com
        dockerfile-path: ./Dockerfile
        input-type: docker-daemon
        ignore-failed-scan: false
        run-as-user: root
    -
      name: Push Docker image
      run: docker push ghcr.io/a-sinkavets/bitcoin:0.21.0
