name: Build Docker Image

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Biuld Docker image and push it to registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # -
    #   name: Build image
    #   env:
    #     PAT: ${{ secrets.GCR_TOKEN }}
    #   run: |
    #     echo $PAT | docker login ghcr.io -u a-sinkavets --password-stdin
    - name: Build Docker image
      run: |
        docker build . --tag ghcr.io/a-sinkavets/bitcoin:0.21.0
        docker run ghcr.io/a-sinkavets/bitcoin:0.21.0
        docker push ghcr.io/a-sinkavets/bitcoin:0.21.0
    #
    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: a-sinkavets/bitcoin:0.21.0
